name: EST
options:
  bundleIdPrefix: com.centaur-labs
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.30.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  EST:
    type: application
    platform: iOS
    sources:
      - path: EST
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_CFBundleDisplayName: EST
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_BUNDLE_IDENTIFIER: com.centaur-labs.est
    entitlements:
      path: EST/EST.entitlements
      properties:
        com.apple.developer.game-center: true
    resources:
      - path: EST/Resources/Assets.xcassets
